# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'


jobs:
- job: build
  displayName: Build Application
  steps:
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'

- deployment: dev_deploy
  displayName: Deploy to dev environment
  environment: Dev
  strategy:
    runOnce:
      preDeploy:
        steps:
        - task: ManualValidation@0
          inputs:
            notifyUsers: 'matteo.pessina@live.com'
            instructions: 'Are u sure to deploy to dev?'
        pool: server
      deploy:
        steps:
        - script: echo "Deploy in Dev!!!!"

- deployment: prod_deploy
  displayName: Deploy to prod environment
  environment: Prod
  strategy:
    runOnce:
      preDeploy:
        steps:
        - task: ManualValidation@0
          inputs:
            notifyUsers: 'matteo.pessina@live.com'
            instructions: 'Are u sure to deploy to prod?'
        pool: server
      deploy:
        steps:
        - script: echo "Deploy in LIVE!!!!"
  

